# Generated by Django 4.1.7 on 2024-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('marriage', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=20)),
                ('Mname', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=20)),
                ('Wnet', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('Dcc', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('desg', models.CharField(max_length=20)),
            ],
        ),
    ]
