# Generated by Django 4.1.7 on 2024-03-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0002_encryptdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptData',
        ),
    ]
