# Generated by Django 4.1.7 on 2024-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0004_encryptdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptdata',
            name='cardnumber',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='encryptdata',
            name='date_cvv',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='encryptdata',
            name='keys',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='encryptdata',
            name='password',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='encryptdata',
            name='pin',
            field=models.CharField(max_length=70),
        ),
    ]
