# Generated by Django 4.1.7 on 2024-03-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0005_alter_encryptdata_cardnumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptData',
        ),
    ]
