# Generated by Django 4.1.7 on 2024-03-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0006_delete_encryptdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('cardnumber', models.CharField(max_length=70)),
                ('date_cvv', models.CharField(max_length=70)),
                ('key1', models.CharField(max_length=70)),
                ('key2', models.CharField(max_length=70)),
                ('pin', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
