# Generated by Django 4.1.7 on 2024-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0008_alter_bankdetails_email_alter_bankdetails_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='Email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='Fname',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='Mname',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='number',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='pin',
            field=models.CharField(max_length=80),
        ),
    ]
