# Generated by Django 4.1.7 on 2024-03-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newimg', models.FileField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
