# Generated by Django 4.1.7 on 2024-03-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdetails',
            name='newimg',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
