# Generated by Django 4.1.7 on 2024-03-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0003_registerdetails_newimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RemoveField(
            model_name='registerdetails',
            name='newimg',
        ),
    ]
