# Generated by Django 4.1.7 on 2024-03-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_rename_image_images_remove_registerdetails_newimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
