# Generated by Django 4.1.7 on 2024-03-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
