# Generated by Django 4.1.7 on 2024-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='newimg',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
