# Generated by Django 4.1.7 on 2024-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0008_alter_image_newimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('productname', models.CharField(max_length=30)),
                ('newimg', models.ImageField(default=None, max_length=250, null=True, upload_to='cart/')),
            ],
        ),
    ]
