# Generated by Django 4.1.7 on 2024-03-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0009_addtocart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='newimg',
            new_name='image',
        ),
    ]
