# Generated by Django 4.1.7 on 2024-03-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0010_rename_newimg_addtocart_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='email',
        ),
    ]
