# Generated by Django 4.1.7 on 2024-03-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0011_rename_name_image_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='email',
            new_name='name',
        ),
    ]
