# Generated by Django 4.1.7 on 2024-03-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0012_rename_email_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='cart/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='newimg',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
