# Generated by Django 4.1.7 on 2024-03-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0014_alter_addtocart_image_alter_image_newimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='newimg',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
