# Generated by Django 4.1.7 on 2024-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0015_alter_addtocart_image_alter_image_newimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='savecarddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('cardnumber', models.CharField(max_length=70)),
                ('date_cvv', models.CharField(max_length=70)),
                ('keys', models.CharField(max_length=70)),
                ('pin', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='cart/'),
        ),
    ]
