# Generated by Django 4.1.7 on 2024-03-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0017_delete_savecarddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='savecarddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('cardnumber', models.CharField(max_length=70)),
                ('date_cvv', models.CharField(max_length=70)),
                ('key1', models.CharField(max_length=70)),
                ('key2', models.CharField(max_length=70)),
                ('pin', models.CharField(max_length=70)),
            ],
        ),
    ]
