# Generated by Django 4.1.7 on 2024-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0018_savecarddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetails',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
